# Generated by Django 4.2.17 on 2025-01-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scryfallcard',
            name='collector_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scryfallcard',
            name='released_at',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='moxfielddeckcard',
            index=models.Index(fields=['board'], name='moxfield_de_board_224499_idx'),
        ),
        migrations.AddIndex(
            model_name='scryfallcard',
            index=models.Index(fields=['released_at', 'collector_number'], name='scryfall_ca_release_1dc48f_idx'),
        ),
    ]
