services:
  app:
    build:
      context: ../app
      dockerfile: ../docker/app/Dockerfile.dev
    container_name: cedhtools-app
    volumes:
      - ../app:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    networks:
      - cedhtools
    restart: always

networks:
  cedhtools:
    