services:
  data-mongodb:
    image: mongo
    container_name: data-mongodb-prod
    ports:
      - ${DATA_INITDB_PORT}:27017
    volumes:
      - data-mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATA_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATA_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATA_INITDB_DATABASE}
    networks:
      - cedhtools
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  user-mongodb:
    image: mongo
    container_name: user-mongodb-prod
    ports:
      - ${USER_INITDB_PORT}:27017
    volumes:
      - user-mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USER_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${USER_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${USER_INITDB_DATABASE}
    networks:
      - user
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build:
      context: ../api
      dockerfile: ../.docker/api/Dockerfile.prod
    container_name: api-prod
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      # RUST
      - RUST_LOG=${RUST_LOG}
      - RUST_BACKTRACE=${RUST_BACKTRACE}
      # API
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      # APP
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      # MONGO
      - MONGO_HOST=${MONGO_HOST}
      # CEDHTOOLS DATABASE
      - DATA_INITDB_ROOT_USERNAME=${DATA_INITDB_ROOT_USERNAME}
      - DATA_INITDB_ROOT_PASSWORD=${DATA_INITDB_ROOT_PASSWORD}
      - DATA_INITDB_DATABASE=${DATA_INITDB_DATABASE}
      - DATA_INITDB_PORT=${DATA_INITDB_PORT}
      - DATA_INITDB_URI=${DATA_INITDB_URI}
      - DATA_INITDB_TABLES=${DATA_INITDB_TABLES}
      # USER DATABASE
      - USER_INITDB_ROOT_USERNAME=${USER_INITDB_ROOT_USERNAME}
      - USER_INITDB_ROOT_PASSWORD=${USER_INITDB_ROOT_PASSWORD}
      - USER_INITDB_DATABASE=${USER_INITDB_DATABASE}
      - USER_INITDB_PORT=${USER_INITDB_PORT}
      - USER_INITDB_URI=${USER_INITDB_URI}
      - USER_INITDB_TABLES=${USER_INITDB_TABLES}
    networks:
      - cedhtools
      - user
    restart: unless-stopped
    depends_on:
      - data-mongodb
      - user-mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # app:
  #   build:
  #     context: ../app
  #     dockerfile: ../.docker/app/Dockerfile.prod
  #   container_name: app-prod
  #   ports:
  #     - ${APP_PORT}:${APP_PORT}
  #   environment:
  #     - NODE_ENV=production
  #     - API_HOST=${API_HOST}
  #     - API_PORT=${API_PORT}
  #     - APP_HOST=${APP_HOST}
  #     - APP_PORT=${APP_PORT}
  #   networks:
  #     - cedhtools
  #   restart: unless-stopped
  #   depends_on:
  #     - api
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"

networks:
  cedhtools:
    driver: bridge
  user:
    driver: bridge

volumes:
  data-mongodb_data:
  user-mongodb_data:
