# Build stage
FROM rust:1.84-slim-bookworm AS builder

WORKDIR /usr/src/app

# Install required system dependencies
RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Install cargo-watch for hot reloading
RUN cargo install cargo-watch

# Create blank project
RUN cargo init

# Copy manifests
COPY Cargo.lock Cargo.toml ./

# Cache dependencies
RUN cargo fetch

# Copy source code
COPY src src

# Development with hot reloading
CMD ["cargo", "watch", "-x", "run"]

# Expose the port
EXPOSE 3100
