# Generated by Django 4.2.17 on 2025-01-02 07:27

import cedhtools_backend.validators.moxfield_url_validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoxfieldBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('mainboard', 'mainboard'), ('commanders', 'commanders'), ('companions', 'companions')], max_length=255)),
            ],
            options={
                'db_table': 'moxfield_board',
            },
        ),
        migrations.CreateModel(
            name='MoxfieldBoardCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'moxfield_board_card',
            },
        ),
        migrations.CreateModel(
            name='MoxfieldCard',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('unique_card_id', models.CharField(blank=True, max_length=255, null=True)),
                ('scryfall_id', models.UUIDField()),
            ],
            options={
                'db_table': 'moxfield_card',
            },
        ),
        migrations.CreateModel(
            name='MoxfieldDeck',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('public_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'moxfield_deck',
            },
        ),
        migrations.CreateModel(
            name='TopdeckTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=255, unique=True)),
                ('tournament_name', models.CharField(max_length=511)),
                ('swiss_num', models.IntegerField()),
                ('start_date', models.BigIntegerField()),
                ('top_cut', models.IntegerField()),
            ],
            options={
                'db_table': 'topdeck_tournament',
                'indexes': [models.Index(fields=['tid'], name='topdeck_tou_tid_a5ba7b_idx'), models.Index(fields=['start_date'], name='topdeck_tou_start_d_77b46e_idx'), models.Index(fields=['top_cut'], name='topdeck_tou_top_cut_02ea6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopdeckPlayerStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511)),
                ('decklist', models.URLField(blank=True, max_length=255, null=True, validators=[cedhtools_backend.validators.moxfield_url_validator.validate_moxfield_url])),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_standings', to='cedhtools_backend.moxfielddeck')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='cedhtools_backend.topdecktournament')),
            ],
            options={
                'db_table': 'topdeck_player_standing',
            },
        ),
        migrations.AddIndex(
            model_name='moxfielddeck',
            index=models.Index(fields=['id'], name='moxfield_de_id_d18690_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfielddeck',
            index=models.Index(fields=['public_id'], name='moxfield_de_public__8460e5_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfieldcard',
            index=models.Index(fields=['unique_card_id'], name='moxfield_ca_unique__bc68ff_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfieldcard',
            index=models.Index(fields=['scryfall_id'], name='moxfield_ca_scryfal_9a73b4_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfieldcard',
            index=models.Index(fields=['id'], name='moxfield_ca_id_d30ae0_idx'),
        ),
        migrations.AddField(
            model_name='moxfieldboardcard',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_cards', to='cedhtools_backend.moxfieldboard'),
        ),
        migrations.AddField(
            model_name='moxfieldboardcard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_cards', to='cedhtools_backend.moxfieldcard'),
        ),
        migrations.AddField(
            model_name='moxfieldboard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='cedhtools_backend.moxfielddeck'),
        ),
        migrations.AddIndex(
            model_name='topdeckplayerstanding',
            index=models.Index(fields=['deck'], name='topdeck_pla_deck_id_783303_idx'),
        ),
        migrations.AddIndex(
            model_name='topdeckplayerstanding',
            index=models.Index(fields=['decklist'], name='topdeck_pla_decklis_6efe1b_idx'),
        ),
        migrations.AddIndex(
            model_name='topdeckplayerstanding',
            index=models.Index(fields=['tournament'], name='topdeck_pla_tournam_b6864b_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfieldboardcard',
            index=models.Index(fields=['board'], name='moxfield_bo_board_i_5def02_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfieldboardcard',
            index=models.Index(fields=['card'], name='moxfield_bo_card_id_a47a38_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfieldboard',
            index=models.Index(fields=['deck'], name='moxfield_bo_deck_id_470644_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfieldboard',
            index=models.Index(fields=['key'], name='moxfield_bo_key_fb19e2_idx'),
        ),
    ]
