# Generated by Django 4.2.17 on 2025-01-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topdeckplayerstanding',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='topdeckplayerstanding',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='topdeckplayerstanding',
            name='name',
        ),
        migrations.RemoveField(
            model_name='topdeckplayerstanding',
            name='wins',
        ),
        migrations.RemoveField(
            model_name='topdecktournament',
            name='tournament_name',
        ),
        migrations.AddField(
            model_name='topdeckplayerstanding',
            name='draw_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topdeckplayerstanding',
            name='loss_rate',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topdeckplayerstanding',
            name='win_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
