# Generated by Django 4.2.17 on 2024-12-12 20:43

import cedhtools_backend.validators.moxfield_url_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstanding',
            name='decklist',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[
                                  cedhtools_backend.validators.moxfield_url_validator.validate_moxfield_url]),
        ),
    ]
