# Generated by Django 4.2.17 on 2024-12-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scryfallcard',
            name='uri',
            field=models.URLField(default='www.test.com', help_text='A link to this card object on Scryfall’s API.'),
            preserve_default=False,
        ),
    ]
