# Generated by Django 4.2.17 on 2025-01-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0002_remove_topdeckplayerstanding_draws_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moxfielddeck',
            name='name',
        ),
    ]
