# Generated by Django 4.2.17 on 2025-01-02 08:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0003_remove_moxfielddeck_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moxfieldboardcard',
            name='board',
        ),
        migrations.RemoveField(
            model_name='moxfieldboardcard',
            name='card',
        ),
        migrations.AddField(
            model_name='moxfieldcard',
            name='deck_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cedhtools_backend.moxfielddeck'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moxfielddeck',
            name='commander_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=None, size=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MoxfieldBoard',
        ),
        migrations.DeleteModel(
            name='MoxfieldBoardCard',
        ),
    ]
