# Generated by Django 4.2.17 on 2024-12-31 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0003_alter_scryfallcardface_cmc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scryfallcard',
            name='card_back_id',
        ),
    ]
