# Generated by Django 4.2.17 on 2024-12-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0004_remove_scryfallcard_card_back_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scryfallcard',
            name='cmc',
            field=models.FloatField(blank=True, help_text='The card’s mana value. Note that some funny cards have fractional mana costs.', null=True),
        ),
    ]
