# Generated by Django 4.2.17 on 2025-01-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0004_remove_moxfieldboardcard_board_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moxfieldcard',
            old_name='deck_id',
            new_name='deck',
        ),
    ]
