# Generated by Django 4.2.17 on 2025-01-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0005_rename_deck_id_moxfieldcard_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moxfieldcard',
            name='deck',
        ),
        migrations.CreateModel(
            name='MoxfieldDeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('board', models.CharField(max_length=50)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedhtools_backend.moxfieldcard')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedhtools_backend.moxfielddeck')),
            ],
            options={
                'db_table': 'moxfield_deck_card',
            },
        ),
        migrations.AddField(
            model_name='moxfieldcard',
            name='decks',
            field=models.ManyToManyField(related_name='cards', through='cedhtools_backend.MoxfieldDeckCard', to='cedhtools_backend.moxfielddeck'),
        ),
        migrations.AddIndex(
            model_name='moxfielddeckcard',
            index=models.Index(fields=['deck', 'card'], name='moxfield_de_deck_id_bdaa07_idx'),
        ),
    ]
