# Generated by Django 4.2.17 on 2024-12-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0005_playerstanding_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moxfieldauthor',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='moxfieldauthor',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldauthor',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='acorn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='border_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_hoarder_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_kingdom_foil_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_kingdom_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_market_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_trader_foil_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_trader_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='cardkingdom_foil_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='cardkingdom_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='cardmarket_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='cmc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='color_indicator',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='colorshifted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='content_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='cool_stuff_inc_foil_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='cool_stuff_inc_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='default_finish',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='etched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='foil',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='frame',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='glossy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='has_arena_legal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='has_multiple_editions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='is_arena_legal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='is_pauper_commander',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='is_token',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='lang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='mana_cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='mtgo_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='multiverse_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='nonfoil',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='oracle_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='promo_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='rarity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='reprint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='scryfall_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='set_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='set_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='set_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='starcitygames_foil_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='starcitygames_foil_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='starcitygames_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='starcitygames_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='tcgplayer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='tcgplayer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='type_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='unique_card_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
