# Generated by Django 4.2.17 on 2024-12-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0005_alter_scryfallcard_cmc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scryfallcard',
            name='color_indicator',
        ),
        migrations.RemoveField(
            model_name='scryfallcardface',
            name='color_indicator',
        ),
        migrations.RemoveField(
            model_name='scryfallcardface',
            name='flavor_text',
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='cmc',
            field=models.FloatField(help_text='The card’s mana value. Note that some funny cards have fractional mana costs.'),
        ),
    ]
