# Generated by Django 4.2.17 on 2025-01-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0006_create_card_printings_mv'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPrintings',
            fields=[
                ('unique_card_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('most_common_printing', models.UUIDField()),
                ('usage_count', models.IntegerField()),
            ],
            options={
                'db_table': 'card_printings',
                'managed': False,
            },
        ),
    ]
