# Generated by Django 4.2.17 on 2024-12-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0006_alter_moxfieldauthor_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moxfieldauthor',
            name='display_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='moxfieldauthor',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldauthor',
            name='username',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
