# Generated by Django 4.2.17 on 2025-01-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0006_remove_moxfieldcard_deck_moxfielddeckcard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moxfielddeck',
            name='commander_ids',
        ),
    ]
