# Generated by Django 4.2.17 on 2024-12-13 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0007_alter_moxfieldauthor_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstanding',
            name='deck',
        ),
    ]
