# Generated by Django 4.2.17 on 2025-01-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0007_remove_moxfielddeck_commander_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScryfallCard',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('scryfall_uri', models.URLField()),
                ('layout', models.CharField(max_length=50)),
                ('type_line', models.CharField(max_length=255)),
                ('mana_cost', models.CharField(blank=True, max_length=50, null=True)),
                ('cmc', models.FloatField()),
                ('legalities', models.JSONField(blank=True, null=True)),
                ('image_uris', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scryfall_card',
            },
        ),
        migrations.AddField(
            model_name='topdeckplayerstanding',
            name='draws',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topdeckplayerstanding',
            name='losses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topdeckplayerstanding',
            name='wins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='topdeckplayerstanding',
            constraint=models.CheckConstraint(check=models.Q(('win_rate__gte', 0), ('win_rate__lte', 1)), name='valid_win_rate'),
        ),
        migrations.AddConstraint(
            model_name='topdeckplayerstanding',
            constraint=models.CheckConstraint(check=models.Q(('draw_rate__gte', 0), ('draw_rate__lte', 1)), name='valid_draw_rate'),
        ),
        migrations.AddConstraint(
            model_name='topdeckplayerstanding',
            constraint=models.CheckConstraint(check=models.Q(('loss_rate__gte', 0), ('loss_rate__lte', 1)), name='valid_loss_rate'),
        ),
        migrations.AddIndex(
            model_name='scryfallcard',
            index=models.Index(fields=['name'], name='scryfall_ca_name_7d8601_idx'),
        ),
    ]
