# Generated by Django 4.2.17 on 2024-12-13 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0008_remove_playerstanding_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstanding',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_standings', to='cedhtools_backend.deck'),
        ),
    ]
