# Generated by Django 4.2.17 on 2025-01-02 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0008_scryfallcard_topdeckplayerstanding_draws_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='topdeckplayerstanding',
            name='valid_win_rate',
        ),
        migrations.RemoveConstraint(
            model_name='topdeckplayerstanding',
            name='valid_draw_rate',
        ),
        migrations.RemoveConstraint(
            model_name='topdeckplayerstanding',
            name='valid_loss_rate',
        ),
    ]
