# Generated by Django 4.2.17 on 2024-12-13 00:17

import cedhtools_backend.validators.moxfield_url_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0009_playerstanding_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='moxfieldauthor',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='playerstanding',
            name='decklist',
            field=models.URLField(blank=True, max_length=100, null=True, validators=[cedhtools_backend.validators.moxfield_url_validator.validate_moxfield_url]),
        ),
        migrations.AlterField(
            model_name='playerstanding',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_name',
            field=models.CharField(max_length=200),
        ),
    ]
