# Generated by Django 4.2.17 on 2024-12-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0010_alter_deck_name_alter_moxfieldauthor_display_name_and_more'),
    ]

    operations = [
    ]
