# Generated by Django 4.2.17 on 2025-01-05 07:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0011_add_refresh_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommanderMetaStatistics',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('commander_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('total_decks', models.IntegerField()),
                ('avg_win_rate', models.FloatField()),
                ('avg_draw_rate', models.FloatField()),
                ('avg_loss_rate', models.FloatField()),
                ('win_rate_stddev', models.FloatField()),
            ],
            options={
                'db_table': 'commander_meta_statistics',
                'managed': False,
            },
        ),
    ]
