# Generated by Django 4.2.17 on 2024-12-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0012_auto_20241213_0643'),
    ]

    operations = [
    ]
