# Generated by Django 4.2.17 on 2024-12-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0013_auto_20241213_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='moxfieldauthor',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_hoarder_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_kingdom_foil_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_kingdom_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_market_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_trader_foil_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_trader_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='cool_stuff_inc_foil_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='cool_stuff_inc_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='starcitygames_foil_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='starcitygames_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='tcgplayer_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
