# Generated by Django 4.2.17 on 2024-12-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0014_alter_deck_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moxfieldcard',
            name='unique_card_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
