# Generated by Django 4.2.17 on 2024-12-13 17:26

import cedhtools_backend.validators.moxfield_url_validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0015_alter_moxfieldcard_unique_card_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoxfieldBoardCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('board_type', models.CharField(max_length=127)),
                ('finish', models.CharField(max_length=127)),
                ('is_foil', models.BooleanField(default=False)),
                ('is_alter', models.BooleanField(default=False)),
                ('is_proxy', models.BooleanField(default=False)),
                ('use_cmc_override', models.BooleanField(default=False)),
                ('use_mana_cost_override', models.BooleanField(default=False)),
                ('use_color_identity_override', models.BooleanField(default=False)),
                ('excluded_from_color', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TopdeckPlayerStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511)),
                ('decklist', models.URLField(blank=True, max_length=255, null=True, validators=[cedhtools_backend.validators.moxfield_url_validator.validate_moxfield_url])),
                ('wins', models.IntegerField(default=0)),
                ('wins_swiss', models.IntegerField(default=0)),
                ('wins_bracket', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(blank=True, null=True)),
                ('win_rate_swiss', models.FloatField(blank=True, null=True)),
                ('win_rate_bracket', models.FloatField(blank=True, null=True)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('losses_swiss', models.IntegerField(default=0)),
                ('losses_bracket', models.IntegerField(default=0)),
                ('player_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopdeckTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=255, unique=True)),
                ('tournament_name', models.CharField(max_length=511)),
                ('swiss_num', models.IntegerField()),
                ('start_date', models.BigIntegerField()),
                ('game', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('top_cut', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='playerstanding',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='playerstanding',
            name='tournament',
        ),
        migrations.AlterField(
            model_name='moxfieldauthor',
            name='display_name',
            field=models.CharField(blank=True, max_length=511),
        ),
        migrations.AlterField(
            model_name='moxfieldauthor',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldauthor',
            name='username',
            field=models.CharField(max_length=511, unique=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='border_color',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_hoarder_url',
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_kingdom_foil_url',
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_kingdom_url',
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_market_url',
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_trader_foil_url',
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='card_trader_url',
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='cardkingdom_foil_id',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='cardkingdom_id',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='cardmarket_id',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='cool_stuff_inc_foil_url',
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='frame',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='lang',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='mtgo_id',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='name',
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='oracle_text',
            field=models.TextField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='rarity',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='set_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='set_type',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='starcitygames_foil_url',
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='starcitygames_url',
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='tcgplayer_id',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='tcgplayer_url',
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
        migrations.RenameModel(
            old_name='Board',
            new_name='MoxfieldBoard',
        ),
        migrations.RenameModel(
            old_name='Deck',
            new_name='MoxfieldDeck',
        ),
        migrations.DeleteModel(
            name='BoardCard',
        ),
        migrations.DeleteModel(
            name='PlayerStanding',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.AddField(
            model_name='topdeckplayerstanding',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_standings', to='cedhtools_backend.moxfielddeck'),
        ),
        migrations.AddField(
            model_name='topdeckplayerstanding',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='cedhtools_backend.topdecktournament'),
        ),
        migrations.AddField(
            model_name='moxfieldboardcard',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_cards', to='cedhtools_backend.moxfieldboard'),
        ),
        migrations.AddField(
            model_name='moxfieldboardcard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_cards', to='cedhtools_backend.moxfieldcard'),
        ),
    ]
