# Generated by Django 4.2.17 on 2024-12-13 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0017_moxfieldhub_moxfieldmedia_moxfielddeck_affiliates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoxfieldCardFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=511)),
                ('mana_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('type_line', models.CharField(blank=True, max_length=255, null=True)),
                ('oracle_text', models.TextField(blank=True, max_length=2047, null=True)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('color_indicator', models.JSONField(blank=True, default=list)),
                ('flavor_text', models.TextField(blank=True, null=True)),
                ('image_seq', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='moxfieldcard',
            name='cedhtools_b_set_cod_b69ebc_idx',
        ),
        migrations.RenameField(
            model_name='moxfieldcard',
            old_name='set_code',
            new_name='set',
        ),
        migrations.RemoveField(
            model_name='moxfielddeck',
            name='media',
        ),
        migrations.AddField(
            model_name='moxfieldcard',
            name='arena_id',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='moxfieldcard',
            name='cn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='moxfielddeck',
            name='owner_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moxfielddeck',
            name='tokens',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_token': True}, related_name='decks_as_tokens', to='cedhtools_backend.moxfieldcard'),
        ),
        migrations.AlterField(
            model_name='moxfieldcard',
            name='acorn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moxfielddeck',
            name='export_id',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='moxfieldcard',
            index=models.Index(fields=['set'], name='cedhtools_b_set_a8cdf1_idx'),
        ),
        migrations.DeleteModel(
            name='MoxfieldMedia',
        ),
        migrations.AddField(
            model_name='moxfieldcardface',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_faces', to='cedhtools_backend.moxfieldcard'),
        ),
    ]
