# Generated by Django 4.2.17 on 2024-12-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0018_moxfieldcardface_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='moxfieldcard',
            name='cedhtools_b_set_a8cdf1_idx',
        ),
        migrations.RenameField(
            model_name='moxfieldcard',
            old_name='set',
            new_name='set_code',
        ),
        migrations.AlterField(
            model_name='moxfieldboard',
            name='key',
            field=models.CharField(choices=[('mainboard', 'mainboard'), ('sideboard', 'sideboard'), ('maybeboard', 'maybeboard'), ('commanders', 'commanders'), ('companions', 'companions'), ('signature_spells', 'signature_spells'), ('attractions', 'attractions'), ('stickers', 'stickers'), ('contraptions', 'contraptions'), ('planes', 'planes'), ('schemes', 'schemes'), ('tokens', 'tokens')], max_length=255),
        ),
        migrations.AlterField(
            model_name='moxfieldboardcard',
            name='board_type',
            field=models.CharField(choices=[('mainboard', 'mainboard'), ('sideboard', 'sideboard'), ('maybeboard', 'maybeboard'), ('commanders', 'commanders'), ('companions', 'companions'), ('signature_spells', 'signature_spells'), ('attractions', 'attractions'), ('stickers', 'stickers'), ('contraptions', 'contraptions'), ('planes', 'planes'), ('schemes', 'schemes'), ('tokens', 'tokens')], max_length=127),
        ),
        migrations.AddIndex(
            model_name='moxfieldcard',
            index=models.Index(fields=['set_code'], name='cedhtools_b_set_cod_b69ebc_idx'),
        ),
    ]
