# Generated by Django 4.2.17 on 2024-12-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0021_topdeckplayerstanding_cedhtools_b_deck_id_90eb51_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='topdeckplayerstanding',
            index=models.Index(fields=['player_id'], name='cedhtools_b_player__bf93ac_idx'),
        ),
    ]
