# Generated by Django 4.2.17 on 2024-12-18 22:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0023_remove_moxfieldcard_cedhtools_b_scryfal_07aa6c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardStatsWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commander_ids', models.JSONField()),
                ('commander_names', models.JSONField()),
                ('unique_card_id', models.CharField(max_length=255)),
                ('card_name', models.CharField(max_length=255)),
                ('week', models.DateField()),
                ('total_decks', models.IntegerField()),
                ('avg_win_rate', models.FloatField()),
                ('avg_draw_rate', models.FloatField()),
            ],
            options={
                'db_table': 'mv_card_stats_weekly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommanderCardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_id', models.CharField(max_length=255)),
                ('tournament_id', models.CharField(max_length=255)),
                ('commander_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('commander_names', models.JSONField()),
                ('card_id', models.CharField(max_length=255)),
                ('unique_card_id', models.CharField(max_length=255)),
                ('card_name', models.CharField(max_length=255)),
                ('total_decks', models.IntegerField()),
                ('avg_win_rate', models.FloatField()),
                ('avg_draw_rate', models.FloatField()),
                ('tournament_size', models.IntegerField()),
                ('start_date', models.BigIntegerField()),
                ('top_cut', models.IntegerField()),
            ],
            options={
                'db_table': 'mv_commander_card_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommanderStatsWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commander_ids', models.JSONField()),
                ('commander_names', models.JSONField()),
                ('week', models.DateField()),
                ('total_decks', models.IntegerField()),
                ('avg_win_rate', models.FloatField()),
                ('avg_draw_rate', models.FloatField()),
            ],
            options={
                'db_table': 'mv_commander_stats_weekly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeckCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_id', models.CharField(max_length=255)),
                ('unique_card_id', models.CharField(max_length=255)),
                ('card_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mv_deck_cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerStandings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerstanding_id', models.CharField(max_length=255)),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('deck_id', models.CharField(max_length=255)),
                ('tournament_id', models.CharField(max_length=255)),
                ('commander_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('commander_names', models.JSONField()),
                ('tournament_size', models.IntegerField()),
                ('top_cut', models.IntegerField()),
                ('start_date', models.BigIntegerField()),
                ('win_rate', models.FloatField()),
                ('draw_rate', models.FloatField()),
            ],
            options={
                'db_table': 'mv_player_standings',
                'managed': False,
            },
        ),
        migrations.RenameIndex(
            model_name='moxfieldboard',
            new_name='moxfield_bo_deck_id_470644_idx',
            old_name='cedhtools_b_deck_id_4a2c5f_idx',
        ),
        migrations.RenameIndex(
            model_name='moxfieldboardcard',
            new_name='moxfield_bo_board_i_5def02_idx',
            old_name='cedhtools_b_board_i_79d262_idx',
        ),
        migrations.RenameIndex(
            model_name='moxfieldboardcard',
            new_name='moxfield_bo_card_id_a47a38_idx',
            old_name='cedhtools_b_card_id_cdd849_idx',
        ),
        migrations.RenameIndex(
            model_name='moxfieldcard',
            new_name='moxfield_ca_name_5fa169_idx',
            old_name='cedhtools_b_name_795cb5_idx',
        ),
        migrations.RenameIndex(
            model_name='moxfieldcard',
            new_name='moxfield_ca_unique__bc68ff_idx',
            old_name='cedhtools_b_unique__384fe3_idx',
        ),
        migrations.RenameIndex(
            model_name='topdeckplayerstanding',
            new_name='topdeck_pla_deck_id_783303_idx',
            old_name='cedhtools_b_deck_id_90eb51_idx',
        ),
        migrations.RenameIndex(
            model_name='topdeckplayerstanding',
            new_name='topdeck_pla_decklis_6efe1b_idx',
            old_name='cedhtools_b_decklis_406cf0_idx',
        ),
        migrations.RenameIndex(
            model_name='topdeckplayerstanding',
            new_name='topdeck_pla_tournam_b6864b_idx',
            old_name='cedhtools_b_tournam_7a2dc6_idx',
        ),
        migrations.RenameIndex(
            model_name='topdeckplayerstanding',
            new_name='topdeck_pla_player__39080d_idx',
            old_name='cedhtools_b_player__bf93ac_idx',
        ),
        migrations.RenameIndex(
            model_name='topdecktournament',
            new_name='topdeck_tou_tid_a5ba7b_idx',
            old_name='cedhtools_b_tid_9494ba_idx',
        ),
        migrations.RenameIndex(
            model_name='topdecktournament',
            new_name='topdeck_tou_start_d_77b46e_idx',
            old_name='cedhtools_b_start_d_3e340d_idx',
        ),
        migrations.RenameIndex(
            model_name='topdecktournament',
            new_name='topdeck_tou_game_40159b_idx',
            old_name='cedhtools_b_game_ce18c1_idx',
        ),
        migrations.RenameIndex(
            model_name='topdecktournament',
            new_name='topdeck_tou_format_7da1f8_idx',
            old_name='cedhtools_b_format_debeeb_idx',
        ),
        migrations.AlterModelTable(
            name='moxfieldauthor',
            table='moxfield_author',
        ),
        migrations.AlterModelTable(
            name='moxfieldboard',
            table='moxfield_board',
        ),
        migrations.AlterModelTable(
            name='moxfieldboardcard',
            table='moxfield_board_card',
        ),
        migrations.AlterModelTable(
            name='moxfieldcard',
            table='moxfield_card',
        ),
        migrations.AlterModelTable(
            name='moxfieldcardface',
            table='moxfield_card_face',
        ),
        migrations.AlterModelTable(
            name='moxfielddeck',
            table='moxfield_deck',
        ),
        migrations.AlterModelTable(
            name='moxfieldhub',
            table='moxfield_hub',
        ),
        migrations.AlterModelTable(
            name='topdeckplayerstanding',
            table='topdeck_player_standing',
        ),
        migrations.AlterModelTable(
            name='topdecktournament',
            table='topdeck_tournament',
        ),
    ]
