# Generated by Django 4.2.17 on 2024-12-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0025_scryfallcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scryfallcard',
            name='oracle_id',
            field=models.UUIDField(null=True),
        ),
    ]
