# Generated by Django 4.2.17 on 2024-12-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0026_alter_scryfallcard_oracle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scryfallcard',
            name='name',
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='oracle_text',
            field=models.TextField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='scryfall_uri',
            field=models.URLField(max_length=511),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='uri',
            field=models.URLField(max_length=511),
        ),
    ]
