# Generated by Django 4.2.17 on 2024-12-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0028_delete_deckcards_alter_moxfieldcard_scryfall_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='moxfieldboard',
            index=models.Index(fields=['key'], name='moxfield_bo_key_fb19e2_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfieldboardcard',
            index=models.Index(fields=['board_type'], name='moxfield_bo_board_t_0ad209_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfieldcard',
            index=models.Index(fields=['scryfall_id'], name='moxfield_ca_scryfal_9a73b4_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfieldcard',
            index=models.Index(fields=['id'], name='moxfield_ca_id_d30ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfieldcard',
            index=models.Index(fields=['color_identity'], name='moxfield_ca_color_i_2e8dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfieldcard',
            index=models.Index(fields=['cmc'], name='moxfield_ca_cmc_79dabe_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfieldcard',
            index=models.Index(fields=['oracle_text'], name='moxfield_ca_oracle__368dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfieldcard',
            index=models.Index(fields=['mana_cost'], name='moxfield_ca_mana_co_59a097_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfieldcard',
            index=models.Index(fields=['colors'], name='moxfield_ca_colors_d403d0_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfielddeck',
            index=models.Index(fields=['id'], name='moxfield_de_id_d18690_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfielddeck',
            index=models.Index(fields=['public_id'], name='moxfield_de_public__8460e5_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfielddeck',
            index=models.Index(fields=['color_identity'], name='moxfield_de_color_i_0bbd2e_idx'),
        ),
        migrations.AddIndex(
            model_name='scryfallcard',
            index=models.Index(fields=['image_uris'], name='scryfall_ca_image_u_33fdf0_idx'),
        ),
        migrations.AddIndex(
            model_name='topdecktournament',
            index=models.Index(fields=['top_cut'], name='topdeck_tou_top_cut_02ea6a_idx'),
        ),
    ]
