# Generated by Django 4.2.17 on 2024-12-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0029_moxfieldboard_moxfield_bo_key_fb19e2_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='moxfieldcard',
            index=models.Index(fields=['type_line'], name='moxfield_ca_type_li_c45ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='moxfieldcard',
            index=models.Index(fields=['legalities'], name='moxfield_ca_legalit_1022ef_idx'),
        ),
    ]
