# Generated by Django 4.2.17 on 2024-12-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0030_moxfieldcard_moxfield_ca_type_li_c45ee9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scryfallcard',
            name='scryfall_ca_image_u_33fdf0_idx',
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='cmc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='color_identity',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='colors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='image_uris',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='lang',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='legalities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='oracle_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='power',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='prices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='scryfall_id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='set_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='toughness',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='type_line',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
