# Generated by Django 4.2.17 on 2024-12-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0032_alter_scryfallcard_scryfall_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scryfallcard',
            name='back_image_uris',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='collector_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='color_identity',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='image_uris',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='lang',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='legalities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='mana_cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='oracle_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='prices',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='rarity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='released_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='scryfall_id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='scryfall_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='set_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='set_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='type_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
