# Generated by Django 4.2.17 on 2024-12-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0034_alter_scryfallcard_back_image_uris_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_id', models.CharField(max_length=255)),
                ('unique_card_id', models.CharField(max_length=255)),
                ('card_id', models.CharField(max_length=255)),
                ('scryfall_id', models.UUIDField()),
                ('card_name', models.CharField(max_length=255)),
                ('card_color_identity', models.JSONField()),
                ('deck_color_identity', models.JSONField()),
            ],
            options={
                'db_table': 'mv_deck_cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.CharField(max_length=255)),
                ('start_date', models.BigIntegerField()),
                ('top_cut', models.IntegerField()),
                ('tournament_size', models.IntegerField()),
            ],
            options={
                'db_table': 'mv_tournament_summary',
                'managed': False,
            },
        ),
    ]
