# Generated by Django 4.2.17 on 2024-12-20 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0035_deckcards_tournamentsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScryfallCardFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mana_cost', models.CharField(blank=True, max_length=50, null=True)),
                ('type_line', models.CharField(blank=True, max_length=255, null=True)),
                ('oracle_text', models.TextField(blank=True, null=True)),
                ('power', models.CharField(blank=True, max_length=50, null=True)),
                ('toughness', models.CharField(blank=True, max_length=50, null=True)),
                ('loyalty', models.CharField(blank=True, max_length=10, null=True)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('image_uris', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'scryfall_card_face',
            },
        ),
        migrations.RemoveField(
            model_name='scryfallcard',
            name='back_image_uris',
        ),
        migrations.RemoveField(
            model_name='scryfallcard',
            name='image_uris',
        ),
        migrations.RemoveField(
            model_name='scryfallcard',
            name='mana_cost',
        ),
        migrations.RemoveField(
            model_name='scryfallcard',
            name='oracle_text',
        ),
        migrations.RemoveField(
            model_name='scryfallcard',
            name='power',
        ),
        migrations.RemoveField(
            model_name='scryfallcard',
            name='toughness',
        ),
        migrations.RemoveField(
            model_name='scryfallcard',
            name='type_line',
        ),
        migrations.AddField(
            model_name='scryfallcard',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scryfallcard',
            name='layout',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scryfallcard',
            name='story_spotlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='oracle_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='scryfall_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='set_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='scryfallcard',
            index=models.Index(fields=['oracle_id'], name='scryfall_ca_oracle__b82e25_idx'),
        ),
        migrations.AddField(
            model_name='scryfallcardface',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='cedhtools_backend.scryfallcard'),
        ),
    ]
