# Generated by Django 4.2.17 on 2024-12-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0037_delete_cardstatsweekly_delete_commandercardstats_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoxfieldCardFace',
        ),
    ]
