# Generated by Django 4.2.17 on 2024-12-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedhtools_backend', '0038_delete_moxfieldcardface'),
    ]

    operations = [
        migrations.AddField(
            model_name='moxfieldcard',
            name='scryfall_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moxfield_cards', to='cedhtools_backend.scryfallcard'),
        ),
    ]
