export const cardConstants = {
  CARD_WIDTH: 200,
  CARD_GAP: 16,
  CORNER_RADIUS_RATIO: 3 / 63,
  BANNER_HEIGHT: 88,
  CARD_ASPECT_RATIO: '63/88',
  STATS_BANNER_HEIGHT: 24,
  STATS_CORNER_HEIGHT: 200,
} as const;
